from typing import Protocol

from node_agent.domain.model.environment_models import GuestSupport, PoolCapability
from node_agent.domain.model.result import Result


class SystemEnvironmentPort(Protocol):
    def get_architecture(self) -> Result[str, Exception]: ...

    def check_hw_virtualization(self) -> Result[bool, Exception]: ...

    def check_nested_virtualization(self) -> Result[bool, Exception]: ...

    def check_selinux_active(self) -> Result[bool, Exception]: ...

    def check_selinux_nfs(self) -> Result[bool, Exception]: ...


class LibvirtEnvironmentPort(Protocol):
    def check_presence(self) -> Result[bool, Exception]: ...

    def get_guest_capabilities(self) -> Result[list[GuestSupport], Exception]: ...

    def get_pool_capabilities(self) -> Result[list[PoolCapability], Exception]: ...
