all:
  children:
    hypervisor_nodes:
      hosts:
        node01:
          ansible_host: 10.140.87.21
        node02:
          ansible_host: 10.140.87.179
        node03:
          ansible_host: 10.140.87.238
        node04:
          ansible_host: 10.140.87.23
      vars:
        ansible_user: "admin"
        ansible_ssh_private_key_file: "~/.ssh/id_rsa"
        ansible_python_interpreter: "/usr/bin/python3"
